- name: play1
  gather_facts: false
  hosts: all
  tasks:
    - name: task1
      ping:

- name: play2
  gather_facts: false
  hosts: all
  become: true
  tasks:        
    - name: update the cache
      apt:
        update_cache: true